# Generated by Django 4.0.2 on 2022-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.CharField(max_length=500)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
